sudo: required

env:
    global:
        - PACKAGE="on_activated_testcase"
        - SUBLIME_TEXT_VERSION="3"
        - UNITTESTING_TAG="master"

matrix:
    include:
        - name: Linux
          os: linux
          language: python
          python: 3.3
        - name: OSX
          os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - sh travis.sh bootstrap
    - sh travis.sh install_package_control

script:
    - sh travis.sh run_tests --coverage

after_success:
    - coveralls

notifications:
    email: true
